# Generated by Django 4.2.23 on 2026-09-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offices', '0010_merge_role_finalize'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('intro_text', models.TextField(blank=True, default='')),
                ('is_office_selector', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bot_menus', to='offices.office')),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_menus', to='bot.botmenu')),
            ],
        ),
        migrations.CreateModel(
            name='BotTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bot_triggers', to='offices.office')),
                ('target_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bot.botmenu')),
            ],
        ),
        migrations.CreateModel(
            name='BotMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200)),
                ('trigger_value', models.CharField(max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('action_type', models.CharField(choices=[('send_text', 'Send text (leaf — completes the session after sending)'), ('show_menu', 'Show another menu'), ('complete_session', 'Complete the session'), ('handoff_to_operator', 'Hand off to a human operator (extension point only)')], max_length=32)),
                ('text', models.TextField(blank=True, default='')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bot.botmenu')),
                ('target_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bot.botmenu')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('fallback_message', models.TextField(blank=True, default='')),
                ('session_completed_message', models.TextField(blank=True, default='')),
                ('office', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bot_config', to='offices.office')),
                ('root_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bot.botmenu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='bottrigger',
            constraint=models.UniqueConstraint(fields=('office', 'keyword'), name='unique_trigger_keyword_per_office'),
        ),
        migrations.AddConstraint(
            model_name='botmenuitem',
            constraint=models.UniqueConstraint(fields=('menu', 'trigger_value'), name='unique_trigger_value_per_menu'),
        ),
        migrations.AddConstraint(
            model_name='botmenu',
            constraint=models.UniqueConstraint(fields=('office', 'name'), name='unique_botmenu_name_per_office'),
        ),
    ]
