# Generated by Django 4.2.23 on 2026-09-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='list_button_text',
            field=models.CharField(blank=True, default='Pilih', max_length=32),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='list_footer_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
