# Generated by Django 4.2.23 on 2026-09-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botconfig_list_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='reply_delay_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
