# Generated by Django 4.2.23 on 2026-09-23 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waha_sessions', '0001_initial'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('destination', models.CharField(max_length=128)),
                ('operation_type', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='pending', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('audit_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_operations', to='audit.auditlog')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_operations', to='waha_sessions.wahasession')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='operations__status_18a66f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='outboundoperation',
            constraint=models.UniqueConstraint(fields=('session', 'idempotency_key'), name='unique_outbound_idempotency_key'),
        ),
    ]
