# Generated by Django 4.2.23 on 2026-09-23 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waha_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkpoint_value', models.CharField(blank=True, max_length=255)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('ok', 'Ok'), ('error', 'Error')], default='idle', max_length=32)),
                ('lag_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sync_checkpoint', to='waha_sessions.wahasession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
