# Generated by Django 4.2.23 on 2026-09-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synccheckpoint',
            name='last_run_task_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='synccheckpoint',
            name='last_run_trigger_source',
            field=models.CharField(blank=True, choices=[('periodic', 'Periodic'), ('targeted', 'Targeted'), ('management_command', 'Management command')], max_length=32),
        ),
    ]
