# Generated by Django 4.2.23 on 2026-09-25 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waha_sessions', '0001_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('sending', 'Sending'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='draft', max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blast_campaigns_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blast_campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blast_campaigns', to='waha_sessions.wahasession')),
            ],
        ),
        migrations.CreateModel(
            name='BlastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=32)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='blast.blastcampaign')),
                ('outbound_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blast_recipients', to='operations.outboundoperation')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='blast_blast_status_244383_idx'), models.Index(fields=['scheduled_for'], name='blast_blast_schedul_c62410_idx'), models.Index(fields=['campaign', 'status'], name='blast_blast_campaig_b984e3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='blastrecipient',
            constraint=models.UniqueConstraint(fields=('campaign', 'destination'), name='unique_blast_campaign_destination'),
        ),
        migrations.AddIndex(
            model_name='blastcampaign',
            index=models.Index(fields=['status'], name='blast_blast_status_f10fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='blastcampaign',
            index=models.Index(fields=['session', 'status'], name='blast_blast_session_a9fead_idx'),
        ),
    ]
