# Generated by Django 4.2.23 on 2026-09-30 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offices', '0011_userprofile'),
        ('blast', '0002_blastcampaign_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('key_prefix', models.CharField(max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlastSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inter_message_delay_seconds', models.PositiveIntegerField(default=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlastTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blastcampaign',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blastrecipient',
            name='variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='blastrecipient',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('invalid_number', 'Invalid number')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='blasttemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blast_templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blasttemplate',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blast_templates', to='offices.office'),
        ),
        migrations.AddField(
            model_name='blastapikey',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blast_api_keys_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blastapikey',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blast_api_keys', to='offices.office'),
        ),
        migrations.AddField(
            model_name='blastcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blast_campaigns', to='blast.blasttemplate'),
        ),
        migrations.AddField(
            model_name='blastcampaign',
            name='triggered_by_api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blast_campaigns', to='blast.blastapikey'),
        ),
        # Moved to the END, after triggered_by_api_key exists — Django's
        # autodetector originally placed this AddConstraint BEFORE the
        # AddField for triggered_by_api_key (the field the constraint
        # itself references), which fails outright on a real Postgres
        # database (FieldDoesNotExist at migrate time). Caught by actually
        # running `migrate` against the real dev DB, not just
        # `makemigrations --check` (which never applies operations, so it
        # can't catch a same-migration ordering bug like this one).
        migrations.AddConstraint(
            model_name='blastcampaign',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), ('triggered_by_api_key__isnull', False)), fields=('triggered_by_api_key', 'idempotency_key'), name='unique_blast_campaign_api_key_idempotency_key'),
        ),
    ]
