# Generated by Django 4.2.23 on 2026-09-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blast', '0003_blastapikey_blastsettings_blasttemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blastapikey',
            name='office',
        ),
    ]
