# Generated by Django 4.2.23 on 2026-09-23 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waha_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_chat_id', models.CharField(max_length=128)),
                ('is_group', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_message_id', models.CharField(max_length=128)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=16)),
                ('message_type', models.CharField(blank=True, max_length=32)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('timestamp', models.DateTimeField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='chats.chat')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='waha_sessions.wahasession')),
            ],
        ),
        migrations.CreateModel(
            name='MediaReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_media_id', models.CharField(blank=True, max_length=128)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('storage_reference', models.CharField(blank=True, max_length=512)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='chats.message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_contact_id', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='waha_sessions.wahasession')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='chats.contact'),
        ),
        migrations.AddField(
            model_name='chat',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chats', to='waha_sessions.wahasession'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'timestamp'], name='chats_messa_chat_id_014e32_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('session', 'provider_message_id'), name='unique_message_per_session'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('session', 'provider_contact_id'), name='unique_contact_per_session'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['session', 'last_message_at'], name='chats_chat_session_06af91_idx'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('session', 'provider_chat_id'), name='unique_chat_per_session'),
        ),
    ]
