# Generated by Django 4.2.23 on 2026-09-28 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_officemembership_role'),
        ('chats', '0002_chat_last_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chats', to='offices.office'),
        ),
    ]
