# Generated by Django 4.2.23 on 2026-09-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chat_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='welcome_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
