# Generated by Django 4.2.23 on 2026-09-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0010_merge_role_finalize'),
        ('bot', '0001_initial'),
        ('chats', '0005_chat_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('waiting_operator', 'Waiting for operator (extension point only — no assignment logic here)'), ('completed', 'Completed')], default='new', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_sessions', to='chats.chat')),
                ('current_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bot.botmenu')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='offices.office')),
            ],
            options={
                'indexes': [models.Index(fields=['chat', 'state'], name='chats_conve_chat_id_3a9ddf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='conversationsession',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['new', 'active', 'waiting_operator'])), fields=('chat',), name='unique_active_conversation_session_per_chat'),
        ),
    ]
