# Generated by Django 4.2.23 on 2026-09-29 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0010_merge_role_finalize'),
        ('chats', '0006_conversationsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='offices.office'),
        ),
    ]
