# Generated by Django 4.2.23 on 2026-09-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_message_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='list_reply_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
