# Generated by Django 4.2.23 on 2026-09-28 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_officemembership_role'),
        ('waha_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wahasession',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waha_sessions', to='offices.office'),
        ),
    ]
