# Generated by Django 4.2.23 on 2026-09-28 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officemembership',
            name='role',
            field=models.CharField(choices=[('global_admin', 'Global Admin'), ('office_admin', 'Office Admin'), ('operator', 'Operator')], default='operator', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='officemembership',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='offices.office'),
        ),
        migrations.AddConstraint(
            model_name='officemembership',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('office__isnull', True), ('role', 'global_admin')), models.Q(('office__isnull', False), ('role__in', ['office_admin', 'operator'])), _connector='OR'), name='office_matches_role'),
        ),
    ]
