# Generated by Django 4.2.23 on 2026-09-28 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_officemembership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeInboxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('welcome_message', models.TextField(blank=True, default='')),
                ('waiting_message', models.TextField(blank=True, default='')),
                ('offline_message', models.TextField(blank=True, default='')),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inbox_config', to='offices.office')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
