# Generated by Django 4.2.23 on 2026-09-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_officeinboxconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='officemembership',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
