# Generated by Django 4.2.23 on 2026-09-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0011_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='visible_menu_items',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
